# Dracula
# Theme create by: https://github.com/BeanieBarrow
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "dracula"

# ========= Border =========
file_panel_border = "#ffffff"
sidebar_border = "#ffffff"
footer_border = "#ffffff"

# ========= Border Active =========
file_panel_border_active = "#ffffff"
sidebar_border_active = "#ffffff"
footer_border_active = "#ffffff"
modal_border_active = "#ffffff"

# ========= Background (bg) =========
full_screen_bg = "#282a36"
file_panel_bg = "#282a36"
sidebar_bg = "#282a36"
footer_bg = "#282a36"
modal_bg = "#282a36"

# ========= Foreground (fg) =========
full_screen_fg = "#f8f8f2"
file_panel_fg = "#f8f8f2"
sidebar_fg = "#f8f8f2"
footer_fg = "#f8f8f2"
modal_fg = "#f8f8f2"

# ========= Special Color =========
cursor = "#905aff"
correct = "#50fa7b"
error = "#ff5555"
hint = "#8be9fd"
cancel = "#6272a4"
# Gradient color can only have two color!
gradient_color = ["#50fa7b", "#ff5555"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#905aff"
file_panel_top_path = "#905aff"
file_panel_item_selected_fg = "#ffb86c"
file_panel_item_selected_bg = "#282a36"

# ========= Sidebar Special Items =========
sidebar_title = "#905aff"
sidebar_item_selected_fg = "#905aff"
sidebar_item_selected_bg = "#282a36"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#f8f8f2"
modal_cancel_bg = "#6272a4"

modal_confirm_fg = "#f8f8f2"
modal_confirm_bg = "#ffb86c"


# ========= Help Menu =========
help_menu_hotkey = "#ffb86c"
help_menu_title = "#905aff"
